"""removed column for pitch_image

Revision ID: 0cd5aee06572
Revises: ae55602904bc
Create Date: 2018-09-11 12:42:42.257354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd5aee06572'
down_revision = 'ae55602904bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'pitch_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
