"""made a relationship btwn the a pitch and a category

Revision ID: 1516fcb2eccf
Revises: 702cd9e6061b
Create Date: 2018-09-10 15:14:39.967045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1516fcb2eccf'
down_revision = '702cd9e6061b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_pitch_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'pitch_id')
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'category', ['category_id'], ['id'])
    op.drop_constraint('users_category_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_category_id_fkey', 'users', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'category_id')
    op.add_column('category', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('category_pitch_id_fkey', 'category', 'pitch', ['pitch_id'], ['id'])
    # ### end Alembic commands ###
