"""Initial Migration

Revision ID: 6704b8f7f396
Revises: b3faadaab5bc
Create Date: 2018-09-10 11:40:10.981649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6704b8f7f396'
down_revision = 'b3faadaab5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date_of_pitch', sa.String(length=255), nullable=True),
    sa.Column('pitch_image', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'pitch', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'pitch_id')
    op.drop_table('pitch')
    # ### end Alembic commands ###
